\documentclass{book}

\usepackage{hyperref}

\usepackage{amsmath}
\usepackage{amsthm}
 
\theoremstyle{definition}
\newtheorem{definition}{Definition}[section]

\newcommand{\union}{\cup}
\newcommand{\intersection}{\cap}

\begin{document}

\title{Statistical Modeling for Research Workers}
\author{Jarad Niemi}
\date{\today}

\maketitle
\newpage

<<child-demo, child='P1C1_probability.Rnw'>>=
@

\end{document}